---
name: "Untitled"
workflowBody:
- function:
    name: "fetchImages"
    type: "Collection"
    dataIns:
    - name: "link"
      type: "string"
    - name: "images"
      type: "collection"
- parallelFor:
    name: "ParallelFor"
    loopCounter: {}
    loopBody:
    - function:
        name: "loadImages"
        type: "fetchImages"
    - function:
        name: "recognizeFace"
        type: "facedetection"
    - function:
        name: "getFaces"
        type: "cropFaces"
    - parallelFor:
        name: "ParallelFor0"
        loopCounter: {}
        loopBody:
        - function:
            name: "moveToBucket"
            type: "boolean"
- function:
    name: "loadImages"
    type: "Collection"
- parallelFor:
    name: "ParallelFor1"
    loopCounter: {}
    loopBody:
    - function:
        name: "findEmotions"
        type: "findEmotionsType"
- function:
    name: "sortFaces"
    type: "Collection"
- parallel:
    name: "Parallel"
    parallelBody:
    - section:
      - switch:
          name: "Switch"
          dataEval: {}
          cases:
          - value: "[Case ...]"
            functions:
            - function:
                name: "moveToBucket"
                type: "boolean"
          - value: "[Case ...]"
            functions:
            - function:
                name: "createCollage"
                type: "Collection"
            - function:
                name: "moveToBucket"
                type: "boolean"
